### ISSUE TITLE
How to compile phyton what i am interested for edit super mario 256

### ISSUE THREAD

**Issue by KielYam1212008** [josh65536/blender-sm256e#1]
![Super Mario 256 Editor Logo](https://user-images.githubusercontent.com/85791629/152663972-effffe56-36f4-4593-8974-dd22eca57f56.png)
Super Mario 256 game ROM hack for to patch .xdelta files (is to/for use program videogame ROM patcher)... I am interested compile files phyton to program super mario 256 editor.
access topics of forum kuribo64: [Post Super Mario 256 Editor](https://kuribo64.net/board/thread.php?id=3119&page=3) and page main [Super Mario 256](https://kuribo64.net/board/thread.php?id=3119&page=1)

**Comment by hayashi-stl** [comment]
what
